[book]
title = "管理自然资本的技术与艺术"
authors = ["Terra"]
language = "zh"
multilingual = false
src = "src"

[output.html]
additional-css = ["custom.css"]

[output.html.playground]
editable = true
copyable = true

